## [심화] 결정 트리 실습 - Human Activity Recognition
-  데이터 전처리를 하여 사이킷런 입력값과 결과값을 설정한다
-  결정트리 모델을 만든다.
-  하이퍼 파라미터 튜닝을 한다(GridSearchCV를 사용해서)
-  중요도를 시각화한다.

In [38]:
import pandas as pd
import numpy as np

In [39]:
print('https://www.kaggle.com/uciml/human-activity-recognition-with-smartphones')

https://www.kaggle.com/uciml/human-activity-recognition-with-smartphones


In [40]:
# train.csv를 받아서 train_score를 만들고, test.csv를 받아서 test_score를 생성하라
human_train_df = pd.read_csv('C:/Users/gihun/Python_Data/data/Human_activity/train.csv')
#train.csv파일을 다운로드 받은 후 humun_train.csv로 변경하시오
#test.csv파일을 다운로드 받은 후 humun_test.csv로 변경하시오
human_test_df = pd.read_csv('C:/Users/gihun/Python_Data/data/Human_activity/test.csv')
# random_state=28
human_train_df.info()
# cv=3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), int64(1), object(1)
memory usage: 31.6+ MB


In [41]:

# human_train.csv를 읽어 df_train 변수에 할당하시오
# human_test.csv를 읽어 df_test변수에 할당하시오


In [42]:
# df_train의 기본 정보를 info() 메소드로 확인하시오


In [43]:
# df_train의 컬럼(열)이름을 확인하시오
human_train_df.columns

Index(['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z',
       'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X',
       ...
       'fBodyBodyGyroJerkMag-kurtosis()', 'angle(tBodyAccMean,gravity)',
       'angle(tBodyAccJerkMean),gravityMean)',
       'angle(tBodyGyroMean,gravityMean)',
       'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)',
       'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'subject', 'Activity'],
      dtype='object', length=563)

In [44]:
# df_train의 클래스(레이블)의 분포를 비율로 확인하시오.
human_train_df.Activity.value_counts(normalize=True)

KeyboardInterrupt: 

In [ ]:
# df_train의 기초 통계량을 describe() 메소드로 확인하시오
human_train_df.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        7352.000000        7352.000000        7352.000000   
mean            0.274488          -0.017695          -0.109141   
std             0.070261           0.040811           0.056635   
min            -1.000000          -1.000000          -1.000000   
25%             0.262975          -0.024863          -0.120993   
50%             0.277193          -0.017219          -0.108676   
75%             0.288461          -0.010783          -0.097794   
max             1.000000           1.000000           1.000000   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       7352.000000       7352.000000       7352.000000       7352.000000   
mean          -0.605438         -0.510938         -0.604754         -0.630512   
std            0.448734          0.502645          0.418687          0.424073   
min           -1.000000         -0.999873         -1.000000         -1.000000   
25%           -0.992754         -0.978129         -0.980233         -0.993591   
50%           -0.946196         -0.851897         -0.859365         -0.950709   
75%           -0.242813         -0.034231         -0.262415         -0.292680   
max            1.000000          0.916238          1.000000          1.000000   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
count       7352.000000       7352.000000       7352.000000  ...   
mean          -0.526907         -0.606150         -0.468604  ...   
std            0.485942          0.414122          0.544547  ...   
min           -1.000000         -1.000000         -1.000000  ...   
25%           -0.978162         -0.980251         -0.936219  ...   
50%           -0.857328         -0.857143         -0.881637  ...   
75%           -0.066701         -0.265671         -0.017129  ...   
max            0.967664          1.000000          1.000000  ...   

       fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
count                      7352.000000                      7352.000000   
mean                         -0.307009                        -0.625294   
std                           0.321011                         0.307584   
min                          -0.995357                        -0.999765   
25%                          -0.542602                        -0.845573   
50%                          -0.343685                        -0.711692   
75%                          -0.126979                        -0.503878   
max                           0.989538                         0.956845   

       angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
count                  7352.000000                           7352.000000   
mean                      0.008684                              0.002186   
std                       0.336787                              0.448306   
min                      -0.976580                             -1.000000   
25%                      -0.121527                             -0.289549   
50%                       0.009509                              0.008943   
75%                       0.150865                              0.292861   
max                       1.000000                              1.000000   

       angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
count                       7352.000000                           7352.000000   
mean                           0.008726                             -0.005981   
std                            0.608303                              0.477975   
min                           -1.000000                             -1.000000   
25%                           -0.482273                             -0.376341   
50%                            0.008735                             -0.000368   
75%                            0.506187                              0.359368   
max                            0.998702                     

In [ ]:
# df_train의 결측치를 확인하시오
#human_train_df[human_train_df.isna()==True]
human_train_df.isnull().sum().sum()

0

In [ ]:
# df_train을 활용하여 X_train, y_train set을 만들고, df_test를 활용하여 X_test, y_test set를 준비하시오

X_train = human_train_df.drop(columns=['Activity','subject']).values
# 혹은 iloc 활용!! X_train = human_train_df.iloc[:,:-2].values
# y 데이터 셋을 라벨인코딩 시킴
y_train = human_train_df.iloc[:,-1].to_numpy()
X_test = human_test_df.iloc[:,:-2].values
y_test = human_test_df.iloc[:,-1].to_numpy()
y_train

array(['STANDING', 'STANDING', 'STANDING', ..., 'WALKING_UPSTAIRS',
       'WALKING_UPSTAIRS', 'WALKING_UPSTAIRS'], dtype=object)

In [ ]:
X_train.shape, X_test.shape

((7352, 561), (2947, 561))

In [ ]:
y_train.shape, y_test.shape

((7352,), (2947,))

In [ ]:
# 레코드 중복 확인
# 데이터프레임 중복 확인:  dataframe.duplicated()
X_train_df = human_train_df.drop(columns=['Activity','subject'])
X_train_df.duplicated().value_counts() # 중복된 레코드가 없다!
# numpy 중복확인은 코딩으로 확인
for i in range(0, len(X_train)-1):
    if ((X_train[i] == X_train[i+1]).sum() == 561):
        print(i)
    else:
        pass

In [ ]:
# 모델 성능 평가
from sklearn.metrics import accuracy_score, precision_score,recall_score
from sklearn.metrics import confusion_matrix, f1_score, roc_auc_score

def get_clf_score(y_test, y_pred):
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    print("-"* 100)
    print("confusion matrix")
    print(cm)
    print("accuracy score: {:.4f}".format(acc))
    return acc

    

#### 결정 트리 모델 구축

In [ ]:
# 모델 구축 및 학습
from sklearn.metrics import accuracy_score, precision_score,recall_score
from sklearn.metrics import confusion_matrix, f1_score, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
x_pred = dt.predict(X_train)
get_clf_score(y_train, x_pred)
y_pred = dt.predict(X_test)
get_clf_score(y_test, y_pred)


----------------------------------------------------------------------------------------------------
confusion matrix
[[1407    0    0    0    0    0]
 [   0 1286    0    0    0    0]
 [   0    0 1374    0    0    0]
 [   0    0    0 1226    0    0]
 [   0    0    0    0  986    0]
 [   0    0    0    0    0 1073]]
accuracy score: 1.0000
----------------------------------------------------------------------------------------------------
confusion matrix
[[537   0   0   0   0   0]
 [  0 374 117   0   0   0]
 [  0  79 453   0   0   0]
 [  0   0   0 454  23  19]
 [  0   0   0  19 352  49]
 [  0   0   0  77  37 357]]
accuracy score: 0.8575


0.8574821852731591

In [46]:
from sklearn.model_selection import GridSearchCV
params = {'min_impurity_decrease':np.arange(0.01, 0.1, 1), # 
        'max_depth':[3,5,7,9,11], # 3, 5, 7, 9, 11
        'min_samples_split':[2,4,6,8,10]} # 2,4,6,8,10 # min_samples_leaf: 2,4,6,8,10
gs = GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)
gs.fit(X_train,y_train)
gs.best_params_

{'max_depth': 5, 'min_impurity_decrease': 0.01, 'min_samples_split': 2}

In [47]:
gs.score(y_test,y_pred)

ValueError: could not convert string to float: 'STANDING'

In [ ]:
# 시각화
import maplotlib.pyplot as plt
from sklearn.tree import plot_tree
plt.figure(figsize=(15,7))
plot_tree(dt, max_depth=1, filled=True, class_names = le.classes_)
plt.show()

In [ ]:

# 하부 코드에 있는 라벨 인코더 객체를 사용했음.


####  y 데이터를 라벨 인코딩한 경우

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

In [ ]:
le.classes_

In [ ]:
# 과적합 및 모델 성능 개선
# 그리드 서치: 10분 이상 걸림